spring:
  datasource:
    password: Memeow1234
    url: jdbc:mysql://memeow452.mysql.database.azure.com:3306/memeow_db?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: memeowadmin@memeow452